const questions = [
  {q: "Hewan apa yang bisa berjalan di dinding?", a: "cicak"},
  {q: "Hewan apa yang bisa berenang di laut?", a: "ikan"},
  {q: "Hewan apa yang bisa melompat jauh?", a: "katak"},
  {q: "Hewan apa yang bisa menggonggong?", a: "anjing"},
  {q: "Hewan apa yang bisa berkokok?", a: "ayam"},
  {q: "Hewan apa yang bisa memanjat pohon?", a: "kucing"},
  {q: "Hewan apa yang bisa membuat sarang dari daun?", a: "burung"},
  {q: "Hewan apa yang bisa berlari sangat cepat?", a: "cheetah"},
  {q: "Hewan apa yang bisa mengeluarkan suara 'moo'?", a: "sapi"},
  {q: "Hewan apa yang bisa memiliki belalai?", a: "gajah"},
  {q: "Hewan apa yang bisa memakan bambu?", a: "panda"},
  {q: "Hewan apa yang bisa menyimpan air di punuknya?", a: "unta"},
  {q: "Hewan apa yang bisa bertanduk dan suka menyeruduk?", a: "banteng"},
  {q: "Hewan apa yang bisa menggigit dan berbisa?", a: "ular"},
  {q: "Hewan apa yang bisa berwarna hitam putih dan hidup di kutub?", a: "pinguin"},
  {q: "Hewan apa yang bisa memiliki cangkang keras?", a: "kura-kura"},
  {q: "Hewan apa yang bisa bertubuh besar dan tinggal di laut?", a: "paus"},
  {q: "Hewan apa yang bisa membuat jaring?", a: "laba-laba"},
  {q: "Hewan apa yang bisa terbang di malam hari?", a: "kelelawar"},
  {q: "Hewan apa yang bisa melompat dengan dua kaki belakang?", a: "kanguru"},
  {q: "Hewan apa yang bisa memiliki surai dan auman keras?", a: "singa"},
  {q: "Hewan apa yang bisa berjalan lambat?", a: "siput"},
  {q: "Hewan apa yang bisa bisa terbang dan berwarna indah?", a: "kupukupu"},
  {q: "Hewan apa yang bisa suka makan wortel?", a: "kelinci"},
  {q: "Hewan apa yang bisa berwarna loreng dan hidup di hutan?", a: "harimau"},
  {q: "Hewan apa yang bisa berjalan mundur?", a: "kepiting"},
  {q: "Hewan apa yang bisa hidup di air tawar dan bersisik?", a: "lele"},
  {q: "Hewan apa yang bisa suka makan keju?", a: "tikus"},
  {q: "Hewan apa yang bisa menyerupai kuda kecil?", a: "kuda poni"},
  {q: "Hewan apa yang bisa punya duri dan bisa menggulung diri?", a: "landak"},
  {q: "Hewan apa yang bisa mengubah warna kulit?", a: "bunglon"},
  {q: "Hewan apa yang bisa berjalan di lumpur dan suka becek?", a: "kerbau"},
  {q: "Hewan apa yang bisa bertanduk dan penghasil susu?", a: "kambing"},
  {q: "Hewan apa yang bisa bisa bernyanyi dan pintar menirukan suara?", a: "beo"},
  {q: "Hewan apa yang bisa punya cakar tajam dan pandai berburu?", a: "elang"},
  {q: "Hewan apa yang bisa bisa terbang rendah dan menghisap madu?", a: "lebah"},
  {q: "Hewan apa yang bisa menggali tanah dan suka di bawah?", a: "tikus mondok"},
  {q: "Hewan apa yang bisa punya sayap bening dan menggigit?", a: "nyamuk"},
  {q: "Hewan apa yang bisa bermata besar dan hidup di malam?", a: "burung hantu"},
  {q: "Hewan apa yang bisa memiliki ekor panjang dan suka bergelantungan?", a: "monyet"},
  {q: "Hewan apa yang bisa berjalan di atas air?", a: "serangga air"},
  {q: "Hewan apa yang bisa berkaki delapan dan hidup di laut?", a: "gurita"},
  {q: "Hewan apa yang bisa berbadan pipih dan suka di sungai?", a: "ikan pari"},
  {q: "Hewan apa yang bisa berwarna hijau dan lompat?", a: "belalang"},
  {q: "Hewan apa yang bisa berbisa dan punya kaki banyak?", a: "kelabang"},
  {q: "Hewan apa yang bisa memiliki cangkang spiral?", a: "siput laut"},
  {q: "Hewan apa yang bisa bertelur di pasir?", a: "penyu"},
  {q: "Hewan apa yang bisa berwarna merah dan mencapit?", a: "rajungan"},
  {q: "Hewan apa yang bisa punya bulu lebat dan lucu?", a: "koala"}
];